
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

locals {
  project_id = var.project_id
  # Use Artifact Registry images when set, else placeholder for Terraform plan
  repo       = var.artifact_registry_repo != "" ? "${var.artifact_registry_repo}" : "us-docker.pkg.dev/cloudrun/container/hello"
  image_tag  = var.image_tag
  frontend_image   = var.artifact_registry_repo != "" ? "${var.artifact_registry_repo}/frontend:${local.image_tag}" : "us-docker.pkg.dev/cloudrun/container/hello"
  backend_image   = var.artifact_registry_repo != "" ? "${var.artifact_registry_repo}/backend-api:${local.image_tag}" : "us-docker.pkg.dev/cloudrun/container/hello"
  planner_image   = var.artifact_registry_repo != "" ? "${var.artifact_registry_repo}/planner-agent:${local.image_tag}" : "us-docker.pkg.dev/cloudrun/container/hello"
  search_image    = var.artifact_registry_repo != "" ? "${var.artifact_registry_repo}/search-agent:${local.image_tag}" : "us-docker.pkg.dev/cloudrun/container/hello"
  retriever_image = var.artifact_registry_repo != "" ? "${var.artifact_registry_repo}/retriever-agent:${local.image_tag}" : "us-docker.pkg.dev/cloudrun/container/hello"
  verifier_image  = var.artifact_registry_repo != "" ? "${var.artifact_registry_repo}/verifier-agent:${local.image_tag}" : "us-docker.pkg.dev/cloudrun/container/hello"
  answer_image    = var.artifact_registry_repo != "" ? "${var.artifact_registry_repo}/answer-agent:${local.image_tag}" : "us-docker.pkg.dev/cloudrun/container/hello"
  reflection_image = var.artifact_registry_repo != "" ? "${var.artifact_registry_repo}/reflection-agent:${local.image_tag}" : "us-docker.pkg.dev/cloudrun/container/hello"
}

module "lb-global-lb-frontend" {
  source        = "github.com/terraform-google-modules/terraform-google-lb-http//modules/frontend?ref=v14.2.0"
  name          = "lb-global-lb-frontend"
  project_id    = coalesce(var.lb-global-lb-frontend_project_id, local.project_id)
  url_map_input = module.lb-global-lb-backend.backend_service_info
}
module "lb-global-lb-backend" {
  source     = "github.com/terraform-google-modules/terraform-google-lb-http//modules/backend?ref=v13.2.0"
  name       = "lb-global-lb-backend"
  project_id = coalesce(var.lb-global-lb-backend_project_id, local.project_id)
  serverless_neg_backends = [{
    region          = module.frontend-service.location
    service_name    = module.frontend-service.service_name
    service_version = ""
    type            = "cloud-run"
  }]
}
module "frontend-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.23.0"
  project_id                    = coalesce(var.frontend-service_project_id, local.project_id)
  location                      = "us-central1"
  service_name                  = "frontend-service"
  containers                    = [{"container_image" = local.frontend_image, "container_name" = "frontend-container", "env_vars" = {"BACKEND_URL" = module.backend-api-gateway.service_uri}}]
  gpu_zonal_redundancy_disabled = false
  create_service_account        = true
  service_account_project_roles = ["roles/run.invoker"]
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "backend-api-gateway" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.23.0"
  project_id                    = coalesce(var.backend-api-gateway_project_id, local.project_id)
  location                      = "us-central1"
  service_name                  = "backend-api-gateway"
  containers                    = [{"container_image" = local.backend_image, "container_name" = "backend-api-gateway-container", "env_vars" = merge({"PLANNER_AGENT_URL" = module.planner-agent.service_uri}, {"SEARCH_AGENT_URL" = module.search-agent.service_uri}, {"RETRIEVER_AGENT_URL" = module.retriever-agent.service_uri}, {"VERIFIER_AGENT_URL" = module.verifier-agent.service_uri}, {"ANSWER_AGENT_URL" = module.answer-agent.service_uri}, {"REFLECTION_AGENT_URL" = module.reflection-agent.service_uri}, {"BIGQUERY_DATASET" = module.bigquery-logging.env_vars.BIGQUERY_DATASET, "BIGQUERY_TABLES" = module.bigquery-logging.env_vars.BIGQUERY_TABLES, "GCS_BUCKET" = module.gcs-document-storage.name, "GCP_PROJECT" = local.project_id})}]
  gpu_zonal_redundancy_disabled = false
  create_service_account        = true
  service_account_project_roles = concat(["roles/run.invoker"], ["roles/run.invoker"], ["roles/run.invoker"], ["roles/run.invoker"], ["roles/run.invoker"], ["roles/run.invoker"], ["roles/bigquery.dataEditor"])
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "planner-agent" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.23.0"
  project_id                    = coalesce(var.planner-agent_project_id, local.project_id)
  location                      = "us-central1"
  service_name                  = "planner-agent"
  containers                    = [{"container_image" = local.planner_image, "container_name" = "planner-agent-container", "env_vars" = {"GCP_PROJECT" = local.project_id}}]
  gpu_zonal_redundancy_disabled = false
  create_service_account        = true
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "search-agent" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.23.0"
  project_id                    = coalesce(var.search-agent_project_id, local.project_id)
  location                      = "us-central1"
  service_name                  = "search-agent"
  containers                    = [{"container_image" = local.search_image, "container_name" = "search-agent-container", "env_vars" = {"GOOGLE_CX" = var.google_cx}, "env_secret_vars" = {"SEARCH_API_KEY" = module.secret-manager.version}}]
  gpu_zonal_redundancy_disabled = false
  create_service_account        = true
  service_account_project_roles = ["roles/secretmanager.secretAccessor"]
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "retriever-agent" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.23.0"
  project_id                    = coalesce(var.retriever-agent_project_id, local.project_id)
  location                      = "us-central1"
  service_name                  = "retriever-agent"
  containers                    = [{"container_image" = local.retriever_image, "container_name" = "retriever-agent-container", "env_vars" = {"GCP_PROJECT" = local.project_id, "GCS_BUCKET" = module.gcs-document-storage.name, "VERTEX_REGION" = "us-central1"}}]
  gpu_zonal_redundancy_disabled = false
  create_service_account        = true
  service_account_project_roles = ["roles/aiplatform.user"]
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  service_labels = {
    vertex_ai_vertex-ai = "true"
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "verifier-agent" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.23.0"
  project_id                    = coalesce(var.verifier-agent_project_id, local.project_id)
  location                      = "us-central1"
  service_name                  = "verifier-agent"
  containers                    = [{"container_image" = local.verifier_image, "container_name" = "verifier-agent-container", "env_vars" = {"GCP_PROJECT" = local.project_id}}]
  gpu_zonal_redundancy_disabled = false
  create_service_account        = true
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "answer-agent" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.23.0"
  project_id                    = coalesce(var.answer-agent_project_id, local.project_id)
  location                      = "us-central1"
  service_name                  = "answer-agent"
  containers                    = [{"container_image" = local.answer_image, "container_name" = "answer-agent-container", "env_vars" = {"GCP_PROJECT" = local.project_id, "VERTEX_REGION" = "us-central1"}}]
  gpu_zonal_redundancy_disabled = false
  create_service_account        = true
  service_account_project_roles = ["roles/aiplatform.user"]
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  service_labels = {
    vertex_ai_vertex-ai = "true"
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "reflection-agent" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.23.0"
  project_id                    = coalesce(var.reflection-agent_project_id, local.project_id)
  location                      = "us-central1"
  service_name                  = "reflection-agent"
  containers                    = [{"container_image" = local.reflection_image, "container_name" = "reflection-agent-container", "env_vars" = {"GCP_PROJECT" = local.project_id, "VERTEX_REGION" = "us-central1"}}]
  gpu_zonal_redundancy_disabled = false
  create_service_account        = true
  service_account_project_roles = ["roles/aiplatform.user"]
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  service_labels = {
    vertex_ai_vertex-ai = "true"
  }
  template_scaling = {
    min_instance_count = 0
  }
}
module "vertex-ai" {
  source        = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v18.0.0"
  project_id    = coalesce(var.vertex-ai_project_id, local.project_id)
  activate_apis = ["aiplatform.googleapis.com"]
}
module "gcs-document-storage" {
  source     = "github.com/terraform-google-modules/terraform-google-cloud-storage//modules/simple_bucket?ref=v12.3.0"
  project_id = coalesce(var.gcs-document-storage_project_id, local.project_id)
  location   = "us-central1"
  name       = "perplexity-document-storage"
  iam_members = [{
    member = module.retriever-agent.service_account_id.member
    role   = "roles/storage.objectAdmin"
  }]
  storage_class = "STANDARD"
}
module "bigquery-logging" {
  source     = "github.com/terraform-google-modules/terraform-google-bigquery?ref=v10.2.1"
  dataset_id = "perplexity_logs"
  project_id = coalesce(var.bigquery-logging_project_id, local.project_id)
  tables = [
    {
      table_id = "query_logs"
      schema    = jsonencode([
        { name = "id", type = "STRING", mode = "REQUIRED", description = "Unique log ID" },
        { name = "query", type = "STRING", mode = "NULLABLE", description = "User query" },
        { name = "response", type = "STRING", mode = "NULLABLE", description = "Final answer" },
        { name = "sources", type = "STRING", mode = "NULLABLE", description = "JSON array of source URLs" },
        { name = "created_at", type = "TIMESTAMP", mode = "NULLABLE", description = "Log timestamp" }
      ])
    }
  ]
}
module "secret-manager" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = coalesce(var.secret-manager_project_id, local.project_id)
  name        = "perplexity-secrets"
  secret_data = var.secret_search_api_key
}
module "apphub" {
  source         = "github.com/GoogleCloudPlatform/terraform-google-apphub?ref=v0.4.0"
  project_id     = coalesce(var.apphub_project_id, local.project_id)
  location       = var.apphub_location
  service_uris   = concat(module.lb-global-lb-frontend.apphub_service_uri, module.lb-global-lb-backend.apphub_service_uri, [module.frontend-service.apphub_service_uri], [module.backend-api-gateway.apphub_service_uri], [module.planner-agent.apphub_service_uri], [module.search-agent.apphub_service_uri], [module.retriever-agent.apphub_service_uri], [module.verifier-agent.apphub_service_uri], [module.answer-agent.apphub_service_uri], [module.reflection-agent.apphub_service_uri], [module.gcs-document-storage.apphub_service_uri])
  application_id = var.apphub_application_id
}
