
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

output "lb-global-lb-frontend_external_ip" {
  description = "The external IPv4 assigned to the global fowarding rule."
  value       = module.lb-global-lb-frontend.external_ip
}
output "lb-global-lb-frontend_external_ipv6_address" {
  description = "The external IPv6 assigned to the global fowarding rule."
  value       = module.lb-global-lb-frontend.external_ipv6_address
}
output "lb-global-lb-frontend_ip_address_internal_managed_http" {
  description = "The internal/external IP addresses assigned to the HTTP forwarding rules."
  value       = module.lb-global-lb-frontend.ip_address_internal_managed_http
}
output "lb-global-lb-frontend_ip_address_internal_managed_https" {
  description = "The internal/external IP addresses assigned to the HTTPS forwarding rules."
  value       = module.lb-global-lb-frontend.ip_address_internal_managed_https
}
output "frontend-service_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.frontend-service.service_uri
}
output "backend-api-gateway_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.backend-api-gateway.service_uri
}
output "planner-agent_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.planner-agent.service_uri
}
output "search-agent_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.search-agent.service_uri
}
output "retriever-agent_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.retriever-agent.service_uri
}
output "verifier-agent_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.verifier-agent.service_uri
}
output "answer-agent_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.answer-agent.service_uri
}
output "reflection-agent_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.reflection-agent.service_uri
}
output "gcs_bucket_name" {
  description = "GCS bucket for document storage"
  value       = module.gcs-document-storage.name
}
output "bigquery_dataset" {
  description = "BigQuery dataset for query logs"
  value       = module.bigquery-logging.env_vars.BIGQUERY_DATASET
}
output "frontend_url" {
  description = "URL of the frontend (via load balancer; use http unless SSL is configured)"
  value       = "http://${module.lb-global-lb-frontend.external_ip}"
}
