
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

# Single project ID for all resources (set in terraform.tfvars)
variable "project_id" {
  description = "GCP project ID for all resources"
  type        = string
}

variable "lb-global-lb-frontend_project_id" {
  description = "The project to deploy to, if not set the default provider project is used."
  type        = string
  default     = null
}
variable "lb-global-lb-backend_project_id" {
  description = "The project to deploy to, if not set the default provider project is used."
  type        = string
  default     = null
}
variable "frontend-service_project_id" {
  description = "The project ID to deploy to"
  type        = string
  default     = null
}
variable "backend-api-gateway_project_id" {
  description = "The project ID to deploy to"
  type        = string
  default     = null
}
variable "planner-agent_project_id" {
  description = "The project ID to deploy to"
  type        = string
  default     = null
}
variable "search-agent_project_id" {
  description = "The project ID to deploy to"
  type        = string
  default     = null
}
variable "retriever-agent_project_id" {
  description = "The project ID to deploy to"
  type        = string
  default     = null
}
variable "verifier-agent_project_id" {
  description = "The project ID to deploy to"
  type        = string
  default     = null
}
variable "answer-agent_project_id" {
  description = "The project ID to deploy to"
  type        = string
  default     = null
}
variable "reflection-agent_project_id" {
  description = "The project ID to deploy to"
  type        = string
  default     = null
}
variable "vertex-ai_project_id" {
  description = "The GCP project you want to enable APIs on"
  type        = string
  default     = null
}
variable "gcs-document-storage_project_id" {
  description = "The ID of the project to create the bucket in."
  type        = string
  default     = null
}
variable "bigquery-logging_project_id" {
  description = "Project where the dataset and table are created"
  type        = string
  default     = null
}
variable "secret-manager_project_id" {
  description = "The project ID to manage the Secret Manager resources"
  type        = string
  default     = null
}
variable "apphub_project_id" {
  description = "The project ID of the host project where AppHub application is created."
  type        = string
  default     = null
}
variable "apphub_location" {
  description = "The location of AppHub application."
  type        = string
  default     = "us-central1"
}
variable "apphub_application_id" {
  description = "The AppHub application identifier"
  type        = string
  default     = "perplexity-ai-demo"
}

# Container image overrides (after building and pushing to Artifact Registry or GCR)
variable "image_tag" {
  description = "Docker image tag for all services"
  type        = string
  default     = "latest"
}

variable "artifact_registry_repo" {
  description = "Artifact Registry repository (e.g. us-central1-docker.pkg.dev/PROJECT_ID/perplexity-demo)"
  type        = string
  default     = ""
}

# Secret for web search (SerpAPI key or Google Custom Search API key). Pass via -var or TF_VAR_secret_search_api_key.
variable "secret_search_api_key" {
  description = "Web search API key (SerpAPI or Google Custom Search). Stored in Secret Manager; used by search-agent."
  type        = string
  default     = "replace-with-google-custom-search-or-serpapi-key"
  sensitive   = true
}

variable "google_cx" {
  description = "Google Programmable Search Engine ID (cx). From your search engine embed code: cx=..."
  type        = string
  default     = ""
}
